### ISSUE TITLE
Display blobs in a folder like structure

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt-hub/core#101]
**Is your feature request related to a problem? Please describe.**
Currently all blobs are shown in a single list while on Cloudflare there are folders.

**Describe the solution you'd like**
A folder like structure for blob data just like the cloudflare dashboard. (maybe just like the ~KV~ Cache admin)

**Comment by Atinux** [comment]
It's out @Gerbuuun ✨ 

https://x.com/nuxt_hub/status/1797571719198105933
