### ISSUE TITLE
can't delete projects, that are deleted on CF

### ISSUE THREAD

**Issue by marcushohlbein** [nuxt-hub/core#110]
**Describe the bug**
If you delete a project on CF, you can't handle it anymore inside the hub dashboard.

**Steps to reproduce**
1. Go to CF pages and remove an existing nuxt hub project
2. Go to nuxt hub dashboard an try to interact with this project
3. You see an error toast, but the project remains inside the dashboard and can't be deleted from

**Expected behavior**
Deleted projects on CF can be deleted from nuxt hub as well (ideally from the dashboard overview)

**Comment by farnabaz** [comment]
Deleting projects from NuxtHub seems to work fine, I just deleted the project from Cloudflare and been able to remove the project in NuxtHub too.
What error did you get when you try to remove the project from dashboard?

**Comment by marcushohlbein** [comment]
<img width="389" alt="Bildschirmfoto 2024-05-17 um 12 25 29" src="https://github.com/nuxt-hub/core/assets/21499846/bdfb33c7-d333-44eb-b396-ebe7e7f58e54">

**Comment by Atinux** [comment]
It should be fixed now!
