### ISSUE TITLE
Hub database displays `undefined` in table data fetch time

### ISSUE THREAD

**Issue by ra-jeev** [nuxt-hub/core#115]
**Describe the bug**
The database table's data fetch time shows `undefined`

**Steps to reproduce**
1. Go to any of your project's hub database in the admin panel
2. Click on any of the tables so that it will fetch its rows (it will correctly display the time it took to fetch, e.g. `725ms`)
3. Now go to some other tabs in the browser, come back to the admin hub tab after some time
4. Refresh the table (from just above the table header) so that it will refetch its rows
5. You'll see `undefined` along with a number

**Expected behavior**
It should not show `undefined` in place of time

Here is a screenshot of the issue (look at `3undefined`. Do not worry about 0 rows, same thing happens where there are rows present)

<img width="1183" alt="Screen Shot 2024-05-19 at 5 11 59 PM" src="https://github.com/nuxt-hub/core/assets/17711017/c8864ede-e4d2-4bdd-8ca0-d58bbd6a13db">

**Comment by Atinux** [comment]
Should be good now!
