### ISSUE TITLE
Nuxt consumes the same amount of CPU even after prerendering (Nuxthub enabled)

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt-hub/core#124]
Even after enabling routeRules prerender in some routes nuxt, some routes still consume the same amount of CPU.

**Comment by rahulkumarsingh73690** [comment]
Is there any way to enable caching to prevent more CPU usage?

**Comment by Atinux** [comment]
Do you have the deployed website or some infos to share to help debug?

**Comment by rahulkumarsingh73690** [comment]
I don't have stats but pre-rendered still counts as a worker request and CPU usage. I have a traffic site where I am facing this issue.

I will try get data from small project

**Comment by rahulkumarsingh73690** [comment]
Please check full discussion on discord with mannil - https://discord.com/channels/473401852243869706/1244656036002926645

**Comment by Atinux** [comment]
So, Nitro cannot follow the link as we did not configure the crawlLinks option but we should not in the hybrid mode

One solution is to use the `prerenderRoutes()`[https://nuxt.com/docs/api/utils/prerender-routes) util in your `blog.vue` page to list all the other blog post pages.

**Comment by rahulkumarsingh73690** [comment]
https://github.com/unjs/nitro/pull/2498
