### ISSUE TITLE
Add a name to a webhook

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/core#127]
Hello 👋,

It could be nice to be able to add a name to a webhook to easily know and recognize them. Actually, the only thing that can change is the URL which can be tricky to use to determine which webhook is used where.

<img width="1457" alt="Screenshot 2024-06-01 at 14 47 16" src="https://github.com/nuxt-hub/core/assets/45267552/673a55c3-8fc9-4449-a1fb-8ea2501696fa">

**Comment by Atinux** [comment]
By looking at other webhooks, I don't see any of them supporting a name field 🤔 

Do you have a lot of webhooks defined?

**Comment by Barbapapazes** [comment]
No, I do not have a lot of webhooks but when you have discord webhooks URLs, it could become very hard to know which is which. But it's just a suggestion and the name could be optional.

**Comment by Atinux** [comment]
It is now possible to set a custom name @Barbapapazes 

As well as selecting the environment :)
