### ISSUE TITLE
Cloudflare failed to publish function

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt-hub/core#13]
I've added `@nuxhub/core` to my existing project and tried to publish it on cloudflare as described in the [docs](https://hub.nuxt.com/docs/getting-started/deploy#self-hosted)
The build is successful but when deploying it fails:

```
Error: Failed to publish your Function. Got error: Uncaught TypeError: Object prototype may only be an Object or null: undefined   at chunks/routes/api/_hub/index.mjs:1:149243 in hn.exports   at chunks/routes/api/_hub/index.mjs:1:173254
```

I have no clue as to what this means. I get no further information at all.
The error happens in `chunks/routes/api/_hub/index.mjs` so I assumed the problems is with `@nuxthub/core`.
The starter template does work so now I'm a bit lost.

`package.json`
If I remember correctly, Nuxt automatically bundles dependencies even if they are dev dependencies.
I tried with putting them in `dependencies` but I still get the same error.
Also, `posthog-node` is supposed to work in serverless environments according to their docs.
```json
{
  ...
  "devDependencies": {
    "@antfu/eslint-config": "^2.8.0",
    "@axiomhq/pino": "1.0.0-rc.2",
    "@formkit/tempo": "^0.0.15",
    "@iconify/json": "^2.2.190",
    "@nuxt/ui-pro": "^1.0.2",
    "@nuxthub/core": "^0.2.1",
    "@vueuse/core": "^10.9.0",
    "dotenv": "^16.4.5",
    "drizzle-kit": "^0.20.14",
    "drizzle-orm": "^0.29.5",
    "eslint": "^8.57.0",
    "nuxt": "^3.10.3",
    "nuxt-auth-utils": "^0.0.20",
    "pino": "^8.19.0",
    "posthog-js": "^1.111.3",
    "posthog-node": "^3.6.3",
    "valibot": "^0.30.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0",
    "wrangler": "^3.31.0"
  }
}
```

```
Nuxt info
------------------------------
- Operating System: Darwin
- Node Version:     v20.8.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, extends, modules, imports, nitro, runtimeConfig, ui, routeRules
- Runtime Modules:  @nuxt/ui@2.14.2, nuxt-auth-utils@0.0.20
- Build Modules:    -
------------------------------
```

**Comment by Gerbuuun** [comment]
And after a long investigation... the culprit is `pino` and `@axiomhq/pino`.
For everyone in the future having this problem... double check your dependencies for Nodejs

**Comment by Atinux** [comment]
Thank you for your feedback and investigation @Gerbuuun 

Indeed this is a bit of a struggle to find librairies that work on the edge, hopefully the whole ecosystem will move toward this (with projects like https://jsr.io/)

It reminds me the UI librairies back then that did not support server-side rendering because they were depending on `window` 😅
