### ISSUE TITLE
Cannot import existing project from Github account

### ISSUE THREAD

**Issue by fermaud** [nuxt-hub/core#133]
**Describe the bug**
I cannot import existing project from my Github account, I gave the access to all my repos and I cannot see any from the select.
![image](https://github.com/nuxt-hub/core/assets/13439156/f4147fcb-7411-4fdf-9d18-24a2c4a034fb)

**Steps to reproduce**
1. Go to https://admin.hub.nuxt.com/fermaud/new/git
2. Click on Repository

**Expected behavior**
As I authorized all my repos I expect to be able to choose on of my repo

**Comment by fermaud** [comment]
Awesome thank you @Atinux !

**Comment by Atinux** [comment]
Re-opening so I can better document it in the dashboard to avoid any similar issue, thanks for reporting ❤️

**Comment by Atinux** [comment]
The admin UI now display a guide on how to properly connect for the first time the GitHub/GitLab integration 😊 

![CleanShot 2024-06-06 at 01 51 06@2x](https://github.com/nuxt-hub/core/assets/904724/636f824b-b0bb-4d33-adcc-16b77c8fa137)
