### ISSUE TITLE
Unable To Import Project From Github Repo

### ISSUE THREAD

**Issue by Sidebridge** [nuxt-hub/core#134]
**Describe the bug**
My github repos couldn't be listed when trying to select a repo project to be imported.

<img width="759" alt="Screenshot 2024-06-04 at 09 32 34" src="https://github.com/nuxt-hub/core/assets/133263455/2a87cb08-7b1d-43fe-ac72-c1e46ae7d3f7">

**Steps to reproduce**
1. Go to [admin.hub.nuxt.com](https://admin.hub.nuxt.com/sidebridge/new/git)
2. Click on 'Select a repository'

**Expected behavior**
I expect that my repos (both public and private) from my Github profile to be listed for selection

**Comment by Atinux** [comment]
Did you install the Cloudflare application @Sidebridge ?

Also, do you have multiple Cloudflare accounts?
