### ISSUE TITLE
docs: should the `blob` path be `file` ?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/core#136]
Hello 👋,

I was reading the documentation about blob and in the server section, https://hub.nuxt.com/docs/storage/blob#serve, we can see a block code:

<img width="797" alt="Screenshot 2024-06-04 at 12 41 23" src="https://github.com/nuxt-hub/core/assets/45267552/faabfbc6-9ea3-4cdd-b848-2e702f6f4061">

The filename contains `file`.

Then, there is a note about using the Vue where the path is `blob`:

<img width="788" alt="Screenshot 2024-06-04 at 12 42 28" src="https://github.com/nuxt-hub/core/assets/45267552/f1a7ab66-b690-4280-95d9-1bf8318f004e">

If I'm well understanding, the path, between these two images should be the same? Or is the `/api/blob` a route built-in core?

**Comment by Atinux** [comment]
Oh nice catch, I think it should be `server/routes/images/[...pathname].get.ts`

Will upadte!
