### ISSUE TITLE
Adopt unstorage Cloudflare KV expiring keys

### ISSUE THREAD

**Issue by darbyjack** [nuxt-hub/core#140]
**Is your feature request related to a problem? Please describe.**
There is currently no way to set an expiration time when setting a key in KV.

**Describe the solution you'd like**
Adopt the updated bindings from unstorage.

**Describe alternatives you've considered**
N/A

**Additional context**
I was requested by Atinux on Discord to open this for tracking purposes.

**Comment by Atinux** [comment]
Thank you for opening and reminding us about it 😄 

The opened PR for unstorage has been merged on https://github.com/unjs/unstorage/pull/423

We are now waiting for the stable release to upgrade it.

**Comment by adamdehaven** [comment]
Let me know if I can help test/verify in a downstream app 🤙🏼

**Comment by atinux** [comment]
It's live with the [v0.7.10](https://github.com/nuxt-hub/core/releases/tag/v0.7.10)!
