### ISSUE TITLE
Export blob types

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/core#141]
Hello 👋,

Do you thing that the blob types, https://github.com/nuxt-hub/core/blob/main/src/runtime/server/utils/blob.ts#L734-L739, could be exported? This could be helpful.

I'm validating a file on the frontend using zod and then on the backend using `ensureBlob` and I want common size and format so I use variables. My issue is that I'm not able to correctly type theses variables for the `ensureBlob` because I do no have access to these types.

**Comment by Atinux** [comment]
Sounds good to me to export some of them yes, happy to open a PR?

**Comment by Barbapapazes** [comment]
Hey,

I'm not sure how to solve this. When I take a look at other packages like nuxt/content or nuxt/fonts, they handle exported types differently. How should I proceed? Is there any recommended way?

**Comment by Atinux** [comment]
Would love to get your expertise on this @farnabaz

**Comment by farnabaz** [comment]
So far I think the best way to expose types in modules is to create a `types/index.ts` file inside src directory and export it via `module.ts`. This way, users can import types easily via module package 

```ts
import { type Foo } from `package`
```

As for `nuxt/content`, we discussed it and in next version types will be exposed from main package too.

**Comment by Barbapapazes** [comment]
If you think you can do it in #130, let's go! Otherwise, I'll wait and make a PR using your advices!

**Comment by RihanArfan** [comment]
I believe this has been resolved now [core/src/types/blob.ts at main · nuxt-hub/core](https://github.com/nuxt-hub/core/blob/main/src/types/blob.ts)

<img src="https://uploads.linear.app/a7d0c16a-b65f-4ab2-8d3e-2583c27d63dc/5f9d7c7e-c92e-42b6-9f12-35e72b8d917b/b13b7225-527b-4bb9-a1ad-b628fd2851a7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3ZDBjMTZhLWI2NWYtNGFiMi04ZDNlLTI1ODNjMjdkNjNkYy81ZjlkN2M3ZS1jOTJlLTQyYjYtOWYxMi0zNWU3MmI4ZDkxN2IvYjEzYjcyMjUtNTI3Yi00YmI5LWExYWQtYjYyOGZkMjg1MWE3IiwiaWF0IjoxNzMxMjE1MjI3LCJleHAiOjMzMzAxNzc1MjI3fQ.Lcf7zYyitubDGI25HwDaLUKJpULhgVCuDxkMHU2WFEI " alt="image.png" width="484" height="313" />

**Comment by Barbapapazes** [comment]
Nice! Thanks!
