### ISSUE TITLE
[Question]: Is R2 integration good for project with large amount of images?

### ISSUE THREAD

**Issue by FutureExcited** [nuxt-hub/core#144]
I'm making a project, which acts as a huuuge gallery of memes. So, naturally there will be like 100-500 memes from user. 

So, I've already have my setup which works by manually fetching objects via aws4fetch/aws-sdk from R2 Bucket. 

My question: is NuxtHub suitable for projects with large amount of objects like this? And does it offer any advantages in working with these images, besides ease of setup? 

Hopium is strong

**Comment by Atinux** [comment]
Hey @FutureExcited 

I don't see any issue of using R2 for that. The main problem might be the size of the images that you want to ensure to not be too big.

We are looking at solution to leverage Nuxt Image based on your Blob, see #131.

Another solution would be to let the user (our your app) to resize the image using something like https://github.com/nodeca/pica

**Comment by FutureExcited** [comment]
Got it, thanks.
