### ISSUE TITLE
Failing migration

### ISSUE THREAD

**Issue by zAlweNy26** [nuxt-hub/core#149]
**Describe the bug**
I don't understand what I am doing wrong in my project. I'm using the starter template (modified ofc) and following the documentation of Nuxt Hub for using Drizzle. The only difference (except for the tables) is the db dialect, `postgresql`. When I generate the migrations everything is ok, but then when I start the project, I see this error in console:
```bash
 ERROR  Database migrations failed D1_ERROR: near "(": syntax error at offset 144

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at SQLiteD1Session.batch (node_modules/src/d1/session.ts:82:24)
  at migrate (node_modules/src/d1/migrator.ts:51:3)
  at <anonymous> (server/plugins/migrations.ts:8:1)
  at async Promise.all (index 0)
  at <anonymous> (node_modules/@nuxthub/core/dist/runtime/ready.dev.js:5:3)
```
 So I'm unable to test the endpoints I created because it doesn't generate the tables. What am I doing wrong?

**Comment by ra-jeev** [comment]
But D1 is not a `postgres` database. 

>[D1 is compatible](https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/) with most SQLite’s SQL convention since it leverages SQLite’s query engine.

**Comment by zAlweNy26** [comment]
> But D1 is not a `postgres` database. 
> 
> >[D1 is compatible](https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/) with most SQLite’s SQL convention since it leverages SQLite’s query engine. 
> 
> Also,
> > [NuxtHub Database](https://hub.nuxt.com/docs/storage/database#:~:text=NuxtHub%20Database%20is%20a%20layer%20on%20top%20of%20Cloudflare%20D1%2C%20a%20serverless%20SQL%20database.) is a layer on top of [Cloudflare D1](https://developers.cloudflare.com/d1), a serverless SQL database.

Ok thanks I missed that part. So there is no way to use postgres?

**Comment by ra-jeev** [comment]
I mean you could use some other `postgres` DB instead of `Cloudflare D1` along with `Drizzle`. That is very much doable.

**Comment by zAlweNy26** [comment]
> I mean you could use some other `postgres` DB instead of `Cloudflare D1` along with `Drizzle`. That is very much doable. 

Can you point me to one of them? I'm not much into Cloudflare

**Comment by ra-jeev** [comment]
> > I mean you could use some other `postgres` DB instead of `Cloudflare D1` along with `Drizzle`. That is very much doable. 
> 
> Can you point me to one of them? I'm not much into Cloudflare

`Cloudflare` doesn't provide a `Postgres` db as far as I know. You could look at other third party providers or self host it.

Some providers are mentioned [in this link](https://hasura.io/learn/database/postgresql/installation/5-postgresql-hosting-providers/)

**Comment by zAlweNy26** [comment]
Thank you so much, I'll look into that. So at the moment I'm unable to use postgres with NuxtHub?

**Comment by ra-jeev** [comment]
> Thank you so much, I'll look into that. So at the moment I'm unable to use postgres with NuxtHub?

The D1 database part from NuxtHub, yes. 

You can still use another Postgres service together with other things from NuxtHub, and host your app on Cloudflare pages using NuxtHub.

**Comment by zAlweNy26** [comment]
Thanks for the clarification and patience, I will definitely do that!

**Comment by Atinux** [comment]
I agree with @ra-jeev said (and thank you for the help!)

For Postgres, Cloudflare worked on Hyperdrive that we plan to support as well in the future: https://developers.cloudflare.com/hyperdrive/

But honestly, D1 is a very powerful database that cover most cases

**Comment by ra-jeev** [comment]
Oooo, didn't know Cloudflare supports existing Postgres DBs. Thanks.

**Comment by atinux** [comment]
To give an update, we now support Hyperdrive bindings and Postgres, see https://hub.nuxt.com/docs/recipes/postgres
