### ISSUE TITLE
Deploy Failed: our Functions script is over the 1 MiB size limit 

### ISSUE THREAD

**Issue by sosensible** [nuxt-hub/core#150]
**Describe the bug**
We have a project we are just starting, and it fails to properly deploy.

 Error: Failed to publish your Function. Got error: Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)

**Steps to reproduce**
1. created project and it all worked well till deployment ending with this message.
 
**Expected behavior**
Deploy and preview.

**Comment by ra-jeev** [comment]
@sosensible As the error message says, with a Cloudflare free plan you can only deploy an app which is 1 MB or less (gzipped). So you must be including a heavy package in your app. You should get a paid plan for your app.

E.g. this is from the build logs for one of my small apps which deploys successfully.
`Σ Total size: 1.17 MB (334 kB gzip)`

This app has the below dependencies
```json
"dependencies": {
  "@iconify-json/simple-icons": "^1.1.104",
  "@nuxt/eslint": "^0.3.13",
  "@nuxt/ui": "^2.16.0",
  "@nuxthub/core": "^0.6.4",
  "@nuxtjs/i18n": "^8.3.1",
  "@nuxtjs/sitemap": "^5.2.0",
  "nuxt": "^3.11.2",
  "nuxt-simple-robots": "4.0.0-rc.17"
}
```

**Comment by Atinux** [comment]
The 1MB worker limit is quite annoying indeed and it can easily go over if you use a package like `@nuxt/content`

Honestly the $5/month plan is the best investment I made so far and you can host up to 500 Nuxt applications with it.

**Comment by sosensible** [comment]
I cannot find which plan says there is an increased limit. They did have a page to sign up for a beta of increased limits. A friend sent me the link, and I am hoping they will do that, but if you have some docs that say the $5 a month will work, I will go ahead and do that.

**Comment by Atinux** [comment]
You can go on https://hub.nuxt.com/pricing and scroll down do the Cloudflare pricing, I worked on regrouping most of their pricing.

When clicking on the Cloudflare Workers card you will be redirected to Cloudflare docs, then on clicking on Limits, you will finally find it: https://developers.cloudflare.com/workers/platform/limits/#worker-size

I know, they should improve their docs/marketing 😅 

But they do have a very competitive pricing as they are in stocks and not a startup anymore and got a very powerful network.

**Comment by sosensible** [comment]
I think I found it, and it was easier than navigating AWS. (a.k.a. less painful, or as you said, they could update these features)

Thanks!!!
