### ISSUE TITLE
Question: Any way to access hubBlob() other way then via /server/api? 

### ISSUE THREAD

**Issue by FutureExcited** [nuxt-hub/core#151]
My app works perfectly on the web, but when I try to port it to desktop via Tauri, I cannot use /server/api.

Because tauri doesn't support ssr.

So is there any way to use hubBlob() not on a server? Or some kind of workaround? Any way at all?

**Comment by Atinux** [comment]
The only solution I can think of for Tauri is to use your API deployed for your web project @FutureExcited

**Comment by FutureExcited** [comment]
Yeah, that's the way I currently do it. Works with no problems, except obviously an additional delay for calling the server.
