### ISSUE TITLE
Unable to Re-import Project from Github Repository After Deleting

### ISSUE THREAD

**Issue by Sidebridge** [nuxt-hub/core#152]
**Describe the bug**
After I deleted a project deployed to Nuxthub (as I wasn't allowed to change the deployment region), I am not able to reimport the project from the same repository again.

**Steps to reproduce**
1. Go to ['Import A Github Repository'](https://admin.hub.nuxt.com/sidebridge/new/git)
2. Click on 'Select a repository'
3. See "<repository> (in use)" when it's not in use

<img width="885" alt="Screenshot 2024-06-08 at 07 32 32" src="https://github.com/nuxt-hub/core/assets/133263455/bd9d4076-ff1d-4439-a9b6-a13ab4ad6287">

**Expected behavior**
I expect that the list resets after deleting a project previously imported via Github repo.

**Comment by Atinux** [comment]
Is the project still on your Cloudflare Pages account @Sidebridge ? I guess you did not check "Delete project's data on Cloudflare" ?

**Comment by Sidebridge** [comment]
@Atinux yes, I didn't select the "Delete project's data on Cloudflare" option while deleting. But I also can't find any project data looking through my Cloudflare dashboard.

Where do I check, How can i fix?

**Comment by Sidebridge** [comment]
This works, thank you
