### ISSUE TITLE
Drizzle ORM changes fields and migration fails

### ISSUE THREAD

**Issue by LBC000** [nuxt-hub/core#155]
**Describe the bug**
Drizzle ORM changes fields and migration fails

**Steps to reproduce**
1. Change schema.ts usersAdmin. add email field
2. Run npm run db:generate; "db:generate": "drizzle-kit generate"
3. Rerun: npx nuxt dev --remote
4. Database migrations failed [POST] "https://xxxxx.cloudflare-nuxthub-02.pages.dev/api/_hub/database/batch": 500

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async $fetch2 (node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
at SQLiteD1Session.batch (node_modules/.pnpm/drizzle-orm@0.31.2_@cloudflare+workers-types@4.20240605.0_@opentelemetry+api@1.8.0/node_modules/src/d1/session.ts:82:24)
at migrate (node_modules/.pnpm/drizzle-orm@0.31.2_@cloudflare+workers-types@4.20240605.0_@opentelemetry+api@1.8.0/node_modules/src/d1/migrator.ts:51:3)
at <anonymous> (server/plugins/migrations.ts:8:1)

**Expected behavior**
Can change fields without error, d1 changes synchronously

<img width="1126" alt="image" src="https://github.com/nuxt-hub/core/assets/33395246/7b46aa82-1d8c-4c6d-b0fc-bcb361dfe862">

**Comment by Atinux** [comment]
Do you have the error locally without the `--remote` @LBC000 ?

**Comment by LBC000** [comment]
> Do you have the error locally without the @LBC000 ?`--remote`

The first time I ran npm run db:generate; "db:generate": "drizzle-kit generate". Then I started the project, and D1 generated the table correctly. This proves that the remote link is correct. But when I want to add a new field, an error is reported, as described above

**Comment by atinux** [comment]
Can you update the dependencies and confirm this is still happening?

**Comment by khawarizmus** [comment]
I am having a similar situation. I didin't have a problem until I added a foreign key to some tables to point to a newly created table.

This was the generated migration file:
```sql
CREATE TABLE `spaces` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`user_id` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE `cards` ADD `space_id` integer REFERENCES spaces(id);--> statement-breakpoint
ALTER TABLE `entries` ADD `space_id` integer REFERENCES spaces(id);--> statement-breakpoint
CREATE INDEX `name_idx` ON `spaces` (`name`);--> statement-breakpoint
/*
 SQLite does not support "Creating foreign key on existing column" out of the box, we do not generate automatic migration for that, so it has to be done manually
 Please refer to: https://www.techonthenet.com/sqlite/tables/alter_table.php
                  https://www.sqlite.org/lang_altertable.html

 Due to that we don't generate migration automatically and it has to be done manually
*/
```

> Can you update the dependencies and confirm this is still happening?

Which dependencies exactly? because I am on the latest drizzle kit and orm.

**Comment by khawarizmus** [comment]
@atinux I just updated the rest of the deps and the problem still persists.

```bash
npx npm-check-updates -u

Upgrading my-project/package.json
[====================] 32/32 100%

 @nuxt/icon         ^1.4.9  →   ^1.4.10
 @nuxthub/core      ^0.7.3  →    ^0.7.5
 @vueuse/core      ^11.0.1  →   ^11.0.3
 lucide-vue-next  ^0.435.0  →  ^0.436.0
 radix-vue          ^1.9.4  →    ^1.9.5

Run npm install to install new versions.
```
I run `npm install` after that. and still got an issue

**Comment by khawarizmus** [comment]
To "fix" this i had to delete my project from both Cloudflare and Nuxthub. re-import it into Nuxthub. delete my migrations folder and regenerate the migrations (it will result in one file). re-link the locale project with remote Nuxthub. run `npm run dev` in remote mode.

Now this is fine because i don't have any data in my database yet and i everything is in development right now. but i can't see this as a solution for a production app.

**Comment by atinux** [comment]
Thanks for investigating @khawarizmus 

Please avoid pinging me multiple times, I read the notifications when I can.

This is a Drizzle issue regarding migration, there is an open issue on it, I recommend you to take a look at the comments there until it's fixed!

https://github.com/drizzle-team/drizzle-orm/issues/1813

**Comment by khawarizmus** [comment]
Apologies for the pinging you multiple times. And thank you for point us to the right Issue.

**Comment by atinux** [comment]
Closing in favour of https://hub.nuxt.com/changelog/database-migrations

**Comment by khawarizmus** [comment]
Does this mean that nuxt hub is the one doing the migration instead of drizzle?

**Comment by atinux** [comment]
The one applying the migrations yes!
