### ISSUE TITLE
onHubReady is not defined

### ISSUE THREAD

**Issue by mhinton** [nuxt-hub/core#158]
**Describe the bug**
When updating from Nuxt 3.11 to 3.12 and @nuxthub/core 0.6.10 to 0.6.12 and using the migration file documented here https://hub.nuxt.com/docs/recipes/drizzle#migrations. On startup I get the following error.
`ERROR  [nitro] [unhandledRejection] onHubReady is not defined`

**Comment by robinsimonklein** [comment]
Same here, got this error even by trying to explicitly import the hook with `import { onHubReady } from '@nuxthub/core/dist/runtime/base/server/utils/hooks';`

**Comment by FutureExcited** [comment]
+1

**Comment by farnabaz** [comment]
This should be Fixed in https://github.com/nuxt-hub/core/releases/tag/v0.6.13
