### ISSUE TITLE
Blob is not enabled in remote project?

### ISSUE THREAD

**Issue by wingchiutong** [nuxt-hub/core#170]
Hi,

I have a NuxtHub project running with AI, KV, and database smoothly on Cloudflare. But blob is not working. I get the following message when running locally:
`Remote storage blob is enabled locally but it's not enabled in the remote project. Deploy a new version with blob enabled to use it remotely.`

I have r2_buckets defined in wrangler.toml, and the following defined in nuxt.config.ts

```ts
  hub: {
    remote: true,
    database: true,
    kv: true,
    blob: true,
    cache: true,
    ai: true,
    vector: true,
  },

```

appreciate anyone's help on this.

Thanks!
Gary

**Comment by Atinux** [comment]
Are you using a local `wrangler.toml` ?

Could you share the `r2_buckets` defined there?
