### ISSUE TITLE
Render gitmojis in commit titles

### ISSUE THREAD

**Issue by RihanArfan** [nuxt-hub/core#175]
**Is your feature request related to a problem? Please describe.**
I use emojis in my commits (https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits) but they aren't rendered in the dashboard.

**Describe the solution you'd like**
_Extremely_ minor QoL feature but would be neat if they rendered.

**Describe alternatives you've considered**
N/A or unicode emojis in commits

**Additional context**
https://gitmoji.dev/

![image](https://github.com/nuxt-hub/core/assets/20425781/e343b272-ce2e-40a8-9a41-5cc85b6c8da0)

![image](https://github.com/nuxt-hub/core/assets/20425781/27d5444e-dc8f-4835-bd50-b20d2dee8236)

**Comment by anbraten** [comment]
Converting the text using sth like https://www.npmjs.com/package/node-emoji should do the trick.
