### ISSUE TITLE
OpenAPI typescript error

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt-hub/core#180]
**Describe the bug**
When enabling openAPI some auto imports are registered
![Scherm­afbeelding 2024-06-20 om 13 12 48](https://github.com/nuxt-hub/core/assets/12988935/2c90c5fb-ad8e-40d1-92ff-43ec0a1125af)
Notice how the file url starts with #. This is not the case with any of the other registered imports.
And Typescript is not happy about this.
![Scherm­afbeelding 2024-06-20 om 13 13 06](https://github.com/nuxt-hub/core/assets/12988935/d760c32d-5b57-46d1-b1dd-d265f84f2e50)

**Steps to reproduce**
1. Set `nitro.experimental.openAPI: true`
2. Generate types (`nuxt prepare` or `pnpm dev` or whatever)
3. See error in `tsconfig.json`

**Expected behavior**
The registered import should be a relative path.
Might be a nitro issue but because the import comes from nuxt-hub I'm raising it here.

**Comment by morcth** [comment]
For me, after running `npx nuxthub init my-app`, `nitro.experimental.openAPI` is already set to true. Did you have to add it to your config?

All I have to do is wait a few minutes after creating a new hub project and my tsconfig.json in root and in .nuxt will turn red and give the baseUrl ts error.

As mentioned in this closed ticket: https://github.com/nuxt-hub/core/issues/97 
Adding: `"compilerOptions": {
		"baseUrl": "./"
	}`
removes the error but I'm not sure it should be ./ in both files

**Comment by Gerbuuun** [comment]
Sure it will solve the error but it might be that nuxthub/nitro does imports incorrectly.
Nuxt generates the `tsconfig.json` for you so you don't have to touch it (zero config, kindof).
To keep it that way, the module should fix the imports or add the `baseUrl` to the `tsconfig.json`

**Comment by morcth** [comment]
Agreed
