### ISSUE TITLE
Local DevTools Blob and KV Bug

### ISSUE THREAD

**Issue by unibeck** [nuxt-hub/core#182]
**Describe the bug**
The Blob and KV sections in DevTools do not show any data when running locally (non-remote)

The API call is returning data as seen in the network tab, just the UI is not showing it.
![image](https://github.com/nuxt-hub/core/assets/15289783/49d388d8-327d-41e4-b57c-e51ac1f4e7ce)

**Steps to reproduce**
1. Run NuxtHub locally (non-remote)
2. Upload a file to Blob storage. Can be done manually through the DevTool or through your app connected to NuxtHub with local bindings
3. See that there is no dat in the Blob DevTool. Same is for KV

**Expected behavior**
For data to show in DevTools when running locally

**Comment by Atinux** [comment]
Could you try again and confirm it works for you now @unibeck ?

Sorry for the slow response.

**Comment by unibeck** [comment]
This is working now, thanks!
