### ISSUE TITLE
remove project error

### ISSUE THREAD

**Issue by devcui** [nuxt-hub/core#189]
After I deleted deployments and all project information in cloudflare, I returned to nuxt hub to delete the project. However, the project could not be deleted due to an error in calling the cloudflare API (probably because I had manually deleted it in cloudflare, which caused the error).

**Comment by farnabaz** [comment]
I couldn't reproduce the issue, tried different scenarios of deleting resources from Cloudflare dashboard and removing project from NuxtHub admin.
Do you mind describing the steps to reproduce the issue?
