### ISSUE TITLE
Minor spelling issue on webhooks page

### ISSUE THREAD

**Issue by Patrity** [nuxt-hub/core#193]
**Describe the bug**
The message states `per-formatted`, should be `preformatted`

**Steps to reproduce**
N/A

**Expected behavior**
N/A

![image](https://github.com/nuxt-hub/core/assets/42813882/ea2afe32-99c0-48e9-b983-11b48df3004e)

**Comment by farnabaz** [comment]
Thanks for the issue, it's patched and will be fixed in next release 🙏
