### ISSUE TITLE
Nuxt 4 support should be turned off by default

### ISSUE THREAD

**Issue by kleenkanteen** [nuxt-hub/core#204]
**Is your feature request related to a problem? Please describe.**
I used the nuxthub starter but also tried deploying the starter on coolify so I get flexbility of using both serverless and a hosted backend api. I wanted to start with hosted and then go serverless in the longterm. The problem is that the default settings of the nuxthub starter supports nuxt 4 which gives issuse while building

I'm trying to deploy my team's starter repo but couldn't get it deployed on a hetzner vps that uses coolify: https://github.com/chingu-voyages/v50-tier3-team-24. 

In `nuxt.config.ts` I removed the line `future: { compatibilityVersion: 4, }` which caused the `.output` folder to originally not get created when running `nuxt build`. I can build it locally but then I get this error when starting it:

```
$ yarn run start
yarn run v1.22.19
$ node .output/server/index.mjs
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'T:\coding\v50-tier3-team-24\.output\server\index.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Tried tried deploying on coolify, which wraps the app in a docker image, but this tim instead of failing its running for 43 mins for some reason. This the last part it's hanging on before I cancelled the deployment any further:

```
[COMMAND] docker exec vwko4cw bash -c 'bash /artifacts/build.sh'
[OUTPUT]
#11 19.58 .../node_modules/workerd postinstall$ node install.js

[2024-Jul-18 03:50:34.491785]

[COMMAND] docker exec vwko4cw bash -c 'bash /artifacts/build.sh'
[OUTPUT]
#11 19.82 .../node_modules/workerd postinstall: Done

[2024-Jul-18 04:32:20.953985] Deployment cancelled by user.
```

**Describe the solution you'd like**
Make the opt-in to nuxt 4 an optional setting during starter setup.

**Comment by Atinux** [comment]
Hi @kleenkanteen 

Actually the NuxtHub module is made to work only on the Cloudflare platform (or the [NuxtHub Admin](https://admin.hub.nuxt.com)
