### ISSUE TITLE
[Admin] Hide delete team button when not possible

### ISSUE THREAD

**Issue by bradley-varol** [nuxt-hub/core#207]
- Register and log in
- Click "Delete team"
- Correctly enter the prompted team name
- Nothing happens when clicking "Delete"
- Pressing enter key works

I suspect this is related to the "can't delete your last team" error which shows when using the enter key.

I think this error should show as a hint below the "Delete team" button. It's better UX not to open the modal, enter the team name and then realise you can't delete the team.

**Comment by Atinux** [comment]
Thanks for the feedback, will iterate and improve the UX soon.

**Comment by darren-flume** [comment]
I had created a second Team as a test and then wanted to delete it (so it was not my final Team) - opening the modal and clicking the delete button would not work (but the button disabled **_correctly_** if I edited the Team name in the input field) - but the _**Enter**_ key trick worked thanks @bradley-varol

**Comment by atinux** [comment]
Sorry it took me so long.

The button is now hidden with an explanation on why you cannot remove the team:
![CleanShot 2024-09-05 at 15 44 14](https://github.com/user-attachments/assets/0e9eb993-26cd-4c2d-bdf1-cc00ef55a0c4)

I also fixed the non-clickable button, thanks for reporting 🙏

**Comment by bradley-varol** [comment]
Nice work! 🚀
