### ISSUE TITLE
[ADMIN| Better error message when call to database fails

### ISSUE THREAD

**Issue by manniL** [nuxt-hub/core#210]
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/130dfea0-d92e-4043-94b2-af0c8bc29f62">

Instead of just showing a 500, show the error message
<img width="566" alt="image" src="https://github.com/user-attachments/assets/927c4829-6b1b-49b1-974a-604145775f30">

**Comment by Atinux** [comment]
Thanks for reporting it @manniL 

It's now fixed!

![CleanShot 2024-07-30 at 18 09 12@2x](https://github.com/user-attachments/assets/c483334d-afce-40b0-a744-2368a20788b6)

Make sure to refresh the tab if already opened :)
