### ISSUE TITLE
[Feature]: Allow linking the same repository to multiple projects

### ISSUE THREAD

**Issue by IsraelOrtuno** [nuxt-hub/core#211]
**Is your feature request related to a problem? Please describe.**
As of now you can't create a project linked to a repository that has been used in another project. As far as I have investigated, CF allows doing so. I guess it's limited by Nuxt Hub internal logic for some reason.

**Describe the solution you'd like**
Would be so nice to be able to deploy as many projects with the same repository as needed.

**Comment by Atinux** [comment]
It's now possible @IsraelOrtuno 🚀 

![CleanShot 2024-07-30 at 17 47 04@2x](https://github.com/user-attachments/assets/6d4d3bef-a0e1-4321-9ce9-8d5e7a3cbb39)

(Make sure to refresh the page)
