### ISSUE TITLE
[Admin Console] "Too many API requests by single worker invocation." when opening large cache

### ISSUE THREAD

**Issue by manniL** [nuxt-hub/core#213]
**Describe the bug**
When opening the `_` group with > 1k cached entries, no entries are shown because the console does too many API request in a single worker call

**Steps to reproduce**
1. Have a cache with > 1k entries (I suppose)
2. Click on Cache in the sidebare
3. Try to open the group
4. See No items

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/62292452-c4b1-424d-b2b7-e01eca41afc4">

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1b31a6da-31ce-480e-bf0f-5dc3c87d74ac">

<img width="592" alt="image" src="https://github.com/user-attachments/assets/31a42047-27ed-49e9-ae7c-a8afde39ecfd">

**Expected behavior**

Working overview

**Comment by Atinux** [comment]
Damn, what do you do with so many cache entries 😂 

The issue comes from https://github.com/nuxt-hub/core/blob/91a1d97436bd1f311c0baeff0e2d40f6b85f0a07/src/runtime/cache/server/api/_hub/cache/%5B...key%5D.get.ts#L29-L50

I think we need to start implementing a pagination, but quite tricky with KV.

**Comment by manniL** [comment]
> Damn, what do you do with so many cache entries 😂
> 
> The issue comes from
> 
> https://github.com/nuxt-hub/core/blob/91a1d97436bd1f311c0baeff0e2d40f6b85f0a07/src/runtime/cache/server/api/_hub/cache/%5B...key%5D.get.ts#L29-L50
> 
> I think we need to start implementing a pagination, but quite tricky with KV.

I have lots of static content from third party APIs which can stay in the cache 👀
But giving easier cache names helped already :P

Yeah, that's a big issue, pagination is a bit meh, though the CF API should allow it at least somehow.
