### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] global is not defined

### ISSUE THREAD

**Issue by dalisys** [nuxt-hub/core#214]
After following the installation guide and configuring Cloudflare, when I deploy my app and try to access it, I get a "500 This page is temporarily unavailable" error, and the logs show the following: 

![image](https://github.com/user-attachments/assets/21a72cd7-5643-4c34-9e9c-ad04681d9d94)

I tried many solutions, and the only one that fixed the problem was to add to nuxt.config.ts:

```ts
vite: {
 define: {
          global: {}
       }
   }
```

However, the issue with this solution, as mentioned in the Vite documentation, is: 
![image](https://github.com/user-attachments/assets/ba28aba8-3c43-4f3d-b9fa-e20a3b35c161)

**My Config**

- Nuxt 3.12.4
- compatibilityVersion: 4 (with the new folder structure)
- wrangler 3.67.1
- @nuxthub/core 0.7.1

**Expected behavior**
Deploy without needing this configuration.

**Comment by Atinux** [comment]
Why and where do you use the `global` variable @dalisys ?

**Comment by dalisys** [comment]
I am not using it anywhere.  

I don't now if its relevant but I am using the unstyled `@primevue/nuxt-module`  with the preset `aura`. And in the `index.js` of the preset they are exporting `global` https://github.com/primefaces/primevue-tailwind/blob/main/presets/aura/index.js

**Comment by Atinux** [comment]
Thanks for looking, it could be this yes.

I created the [Debug mode recipe](https://hub.nuxt.com/docs/recipes/debug), could you try it and confirm the error comes from the Aura preset?

**Comment by dalisys** [comment]
I'm not sure what happened, but everything seems to be working fine now. I also redeployed the old branches where I was experiencing the error, and now they're functioning correctly. Thanks for your help.

**Comment by dalisys** [comment]
@Atinux  I'm experiencing the error again. After multiple attempts, here’s what I’ve observed:


### Vsharp
I'm using the Vitue Vsharp plugin, which apparently triggers this error (I tested configurations both with and without `vite: define: global` in `nuxt.config`):
![with_and_no_global_vharp_amd_1](https://github.com/user-attachments/assets/7826a57b-b625-407d-9c16-6b91d927f8f0)

![no_global_vharp_amd_2](https://github.com/user-attachments/assets/4cfe4ab1-e341-4a08-a2c3-9ddb1c02b9e9)



### SupaBase

I removed Vsharp to fix the issue, but then the original error came back. I started rolling back changes and discovered that the error appeared after adding the Supabase module `"@nuxtjs/supabase": "^1.3.5"`.
Also with `vite: define: global` in `nuxt.config`


![with_global_amd_2](https://github.com/user-attachments/assets/9ea04ca0-6fc9-4390-ac82-0849b7a7a711)

![image](https://github.com/user-attachments/assets/76bbbfb6-94dc-4e75-a428-f3b49215bdf5)


PS: I retested vsharp without the Supabase module, and although the (vsharp) errors were still present, the app worked, and I was able to access it.
