### ISSUE TITLE
[Admin Console] Can't delete database entries without id

### ISSUE THREAD

**Issue by manniL** [nuxt-hub/core#216]
Tried to delete the drizzle migration entry in my preview DB and failed (silently) because no ID exists.

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/87482ef3-3744-4278-8f5a-59a063e45c78">

**Comment by manniL** [comment]
Okay, apparently this is an issue in the cloudflare overview page too 🙈

Happy to close if that's a root problem in CF.

**Comment by Atinux** [comment]
Asking the Drizzle team before to see if we can have some workarounds.

**Comment by Atinux** [comment]
This should be fixed now with a warning to let you open the SQL editor:
![CleanShot 2024-08-02 at 14 24 27@2x](https://github.com/user-attachments/assets/b01e4ffc-d5f3-4e69-8e50-75790ddc2d55)
