### ISSUE TITLE
[Admin] No Cache groups shown when using custom groups

### ISSUE THREAD

**Issue by manniL** [nuxt-hub/core#229]
**Describe the bug**

View in NuxtHub

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/a75e4def-eace-45a2-b8f0-7a2b963daa23">

View in CF itself (through the button in NuxtHub)

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/600e4530-03bc-4851-9b67-aa748560182e">

Example for custom cache group:

```ts
export const getStaticStats = defineCachedFunction((_event: H3Event) => myOtherFn(), {
  group: 'nexon-static',
  getKey: (_event) => 'stats-list',
  maxAge: CACHE_TIME.ONE_DAY,
})
```

**Steps to reproduce**
1. Create a project and ensure a cached function or handler has a custom cache group 
2. Deploy via CF and Nuxt Hub
3. Cache items 
4. See that NuxtHub has no cache entries shown

**Expected behavior**

Showing Custom cache groups (or just an "all" list as fallback?).

**Comment by atinux** [comment]
I can confirm it's in my todo list, thanks for creating the issue 🙏
