### ISSUE TITLE
520 Error When Navigating to Database Section in NuxtHub Account

### ISSUE THREAD

**Issue by chihebnabil** [nuxt-hub/core#230]
I'm encountering a 520 error when navigating to the database section in the NuxtHub account . 

This issue occurs specifically when attempting to perform a database query via the Drizzle API.

**Steps to reproduce the behavior:**

- Go to the NuxtHub account and select a project.
- Navigate to the database section.
- See the 520 error [stacktrace.txt](https://github.com/user-attachments/files/16639051/stacktrace.txt)

**Expected behavior**
Navigating to the database section and performing a query should complete successfully without encountering a 520 error.

**Comment by atinux** [comment]
Can you confirm this happens all the time?

**Comment by chihebnabil** [comment]
@atinux it happned earlier today, it seems fixed now
