### ISSUE TITLE
Question: max app size of 1MB in CF free tier

### ISSUE THREAD

**Issue by remihuigen** [nuxt-hub/core#234]
The [Settings > Cloudflare account page] (https://admin.hub.nuxt.com/onderwijsin/settings/cloudflare) will give the following notification when using CF's free tier:

> You are using Cloudflare Workers Free, we highly encourage to upgrade to Workers Paid plan to remove the 1 MB limit on the final, compressed, bundle size and more.

Is this actually true? Could not find anything on this limitation is CF docs... Besides, my lastest deployment is ``Σ Total size: 4.15 MB (1.19 MB gzip)`` and it works just fine!

**Comment by atinux** [comment]
The limit is described here: https://developers.cloudflare.com/workers/platform/limits/#worker-size

Well I guess it's maybe how we calculate the size or they have some kind of allowance, let's see how big it can fit in the workers free plan 😄

**Comment by remihuigen** [comment]
We'll, ``Σ Total size: 5.96 MB (2.18 MB gzip)`` failed 😅. So i guess its somewhere between 1.19 - 2.18

**Comment by atinux** [comment]
Thanks for helping investigate @remihuigen 😄

**Comment by numberslk** [comment]
` ERROR  [POST] "https://admin.hub.nuxt.com/api/teams/numberslk/projects/numberslk/deploy": 500 Internal Server Error       8:01:42 PM`

I thought this was the error first. But I am keep getting the 500 error. Is there any place I can check the deployment logs? to see where it failed?

**Comment by RihanArfan** [comment]
> ` ERROR [POST] "https://admin.hub.nuxt.com/api/teams/numberslk/projects/numberslk/deploy": 500 Internal Server Error 8:01:42 PM`
> 
> I thought this was the error first. But I am keep getting the 500 error. Is there any place I can check the deployment logs? to see where it failed?

@numberslk See https://github.com/nuxt-hub/cli#debug
