### ISSUE TITLE
Problem with AI binding 

### ISSUE THREAD

**Issue by carloslato** [nuxt-hub/core#237]
I'm trying to use AI binding and work well in localhost but at deploying i'm getting the following error in the server routes:

Missing Cloudflare AI binding (AI)

**Steps to reproduce**
- Use ai binding and LLM model.

**Expected behavior**
Work in local and edge

**Comment by carloslato** [comment]
I was using Cloudflare pages CI, I created the project using HELLO EDGE template from nuxt hub admin.

thanks, now it works with `npx nuxthub deploy`, but when I commit to save my fields in the repository it will deploy again, how do I avoid that?

**Comment by atinux** [comment]
Well it should create the bindings automatically when you deploy using the Cloudflare Pages CI with the `@nuxthub/core` module normally.<br><br>You can create another branch to avoid deploying on each new commit.
