### ISSUE TITLE
"Roadmap" is not showing links

### ISSUE THREAD

**Issue by onmax** [nuxt-hub/core#253]
**Describe the bug**

It fails to load data from API: 

```
Access to fetch at 'https://api.volta.net/repositories/nuxt-hub/core/issues?page=1' from origin 'https://volta.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

![image](https://github.com/user-attachments/assets/32bcab68-4658-4ada-ac49-32eff110ccc4)

**Steps to reproduce**
1. Go to dahsboard
2. Click 'Roadmap'

**Expected behavior**
See the roadmap, not error

**Comment by atinux** [comment]
Do you still have it?
![CleanShot 2024-09-01 at 16 40 06@2x](https://github.com/user-attachments/assets/4faf08c9-0002-4115-93b9-1d50809832b6)

**Comment by onmax** [comment]
Works now. Thanks
