### ISSUE TITLE
NuxtHub Login stuck on admin.hub.nuxt.com

### ISSUE THREAD

**Issue by sreeharsha-rav** [nuxt-hub/core#254]
**Describe the bug**
After trying to deploy using nuxthub deploy, redirects me to login at nuxthub, after using github to login, does not proceed ahead, gets stuck at same page.
I disabled the adblocker as well, but I don't think it would cause the issue, not sure why it's not loading, tried with another browser profile, was able to get it to work.

Browser: Chrome Version 127.0.6533.100 (Official Build) (64-bit)
OS: Windows 11

https://github.com/user-attachments/assets/bff0f7fd-7858-4a3a-afd3-5806ce773288

**Steps to Reproduce:**
1. Login to NuxtHub using github
2. Wait to login

**Expected behavior**
Bypass login and proceed to nuxt deploy.

**Comment by atinux** [comment]
Could you try again @sreeharsha-rav ?

What is your Browser?

**Comment by designbyfaizi** [comment]
I am facing the same issue. I'm trying Nuxthub for the first time. I am using Arc Browser.

**Comment by designbyfaizi** [comment]
Ok just tested on Brave and chrome. Working on both of these browsers. Arc seems to have some issues and does not allow me to proceed from the login page.

**Comment by sreeharsha-rav** [comment]
@atinux I updated the description, it was an issue on chrome, I tried to debug, not sure why it's not loading. It did work on a different chrome profile tho.

**Comment by atinux** [comment]
The solution is to clear your cookies and try again, sorry about this.
