### ISSUE TITLE
question: how to see local database

### ISSUE THREAD

**Issue by samulefevre** [nuxt-hub/core#27]
I use drizzle, i tried to use drizzle studio but can't make it work.

**Comment by Atinux** [comment]
Similar to #23 

The main issue is that the path of the SQLite cannot be guessed because of miniflare.

**Comment by Atinux** [comment]
Should be possible now without any configuration: https://hub.nuxt.com/docs/storage/database#nuxt-devtools

**Comment by samulefevre** [comment]
Thank you !
