### ISSUE TITLE
[wrangler dev] Can't resolve `node:async_hooks`

### ISSUE THREAD

**Issue by remihuigen** [nuxt-hub/core#273]
**Describe the bug**
Running nuxt build with cloudflare-pages preset, and ``npx wrangler pages dev dist/`` results in

```
✘ [ERROR] service core:user:worker: Uncaught Error: No such module "node:async_hooks".

    imported from "r4j10pyoufr.js"


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

```

Introduced somewhere after 0.7.9

**Comment by adamkasper** [comment]
I’m having the same problem when running `npx wrangler pages dev dist/`. In the NuxtHub admin, I get this error:

```
Error: Failed to publish your Function. Got error: Uncaught ReferenceError: global is not defined
  at chunks/runtime.mjs:1:30924
```

**Comment by atinux** [comment]
@adamkasper this is not related to the main issue, see https://github.com/nuxt-hub/core/issues/261#issuecomment-2331005112 (should be fixed in upcoming Nuxt release)

**Comment by atinux** [comment]
Let me have a look @remihuigen

**Comment by remihuigen** [comment]
Sorry, I wasn't clear. Got this error in local dev, not in production

Was debugging as described on https://hub.nuxt.com/docs/recipes/debug

**Comment by remihuigen** [comment]
To confirm: I'm not getting the error in production

**Comment by remihuigen** [comment]
Sure, no problem. 

Didn't get these errors though when following https://hub.nuxt.com/docs/recipes/debug with v0.7.9, so i'd thought a new issue was in order :)

**Comment by ra-jeev** [comment]
The issue here is that the preview should be running in `nodejs_compat` mode which is enabled by default when you deploy it in production. 

For local workers you get this warning first while compiling, and then on runtime you get the above error:
```
 [WARNING] The package "node:async_hooks" wasn't found on the file system but is built into node.

  Your Worker may throw errors at runtime unless you enable the "nodejs_compat" compatibility flag.
  Refer to https://developers.cloudflare.com/workers/runtime-apis/nodejs/ for more details. Imported
  from:
```

Faced the same issue yesterday while trying to preview the build locally.

**Comment by atinux** [comment]
As a workaround you can create a `wrangler.toml` at the root of your project (will be used only for the preview)

```toml
 compatibility_flags = ["nodejs_compat_v2"]
```

**Comment by atinux** [comment]
Alright it's live! https://hub.nuxt.com/changelog/nuxthub-preview

It should work now with:

```bash
npx nuxthub preview
```

**Comment by ra-jeev** [comment]
@atinux This works great. But in the build output I see that the wrangler command is being shown for preview. 

But the codebase shows `npx nuxthub preview`, do I need to update something (I updated `NuxtHub CLI` and `@nuxthub/core`)?

<img width="440" alt="Screen Shot 2024-09-17 at 11 07 25 AM" src="https://github.com/user-attachments/assets/c5741b6a-8ab9-48c2-9f6b-aa36b8d5a61e">

**Comment by ra-jeev** [comment]
In the build output (`pnpm build`)

<img width="699" alt="Screen Shot 2024-09-17 at 4 54 50 PM" src="https://github.com/user-attachments/assets/e0980771-dc9d-45e4-acc0-5e74a574928a">

**Comment by atinux** [comment]
My bad, should be good with [https://github.com/nuxt-hub/core/releases/tag/v0.7.19](https://github.com/nuxt-hub/core/releases/tag/v0.7.19)
