### ISSUE TITLE
require() of ES Module string-width

### ISSUE THREAD

**Issue by michaelsieminski** [nuxt-hub/core#282]
**Describe the bug**
After updating from 0.7.12 to 0.7.15 I'm getting the following Error when deploying to Cloudflare:

`
01:45:45.604 [error] require() of ES Module /opt/buildhome/repo/node_modules/string-width/index.js from /opt/buildhome/repo/node_modules/wide-align/align.js not supported.
01:45:45.604 Instead change the require of index.js in /opt/buildhome/repo/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
01:45:45.604   Instead change the require of index.js in node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
01:45:45.604   at Object.<anonymous> (node_modules/wide-align/align.js:2:19)
01:45:45.605   at Object.<anonymous> (node_modules/gauge/render-template.js:2:13)
01:45:45.605   at Object.<anonymous> (node_modules/gauge/plumbing.js:3:22)
01:45:45.605   at Object.<anonymous> (node_modules/gauge/index.js:2:16)
01:45:45.605   at Object.<anonymous> (node_modules/npmlog/log.js:3:13)
01:45:45.605   at Object.<anonymous> (node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:23:13)
01:45:45.605   at Object.<anonymous> (node_modules/@vercel/nft/out/analyze.js:22:40)
01:45:45.605   at Object.<anonymous> (node_modules/@vercel/nft/out/node-file-trace.js:31:35)
01:45:45.605   at Object.<anonymous> (node_modules/@vercel/nft/out/index.js:22:25) 
01:45:45.605 
01:45:45.605 [error] require() of ES Module /opt/buildhome/repo/node_modules/string-width/index.js from /opt/buildhome/repo/node_modules/wide-align/align.js not supported.
01:45:45.605 Instead change the require of index.js in /opt/buildhome/repo/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
01:45:45.612 
01:45:45.612  1407 packages installed [5.77s]
01:45:45.612 error: script "postinstall" exited with code 1 (SIGHUP)
01:45:45.621 Error: Exit with error code: 1
01:45:45.621     at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
01:45:45.622     at Object.onceWrapper (node:events:652:26)
01:45:45.622     at ChildProcess.emit (node:events:537:28)
01:45:45.622     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
01:45:45.631 Failed: build command exited with code: 1
01:45:46.554 Failed: error occurred while running build command
`

**Expected behavior**
No error

**Comment by atinux** [comment]
You only updated `@nuxthub/core`?

**Comment by michaelsieminski** [comment]
> You only updated `@nuxthub/core`?

Yes exactly, also when I downgrade again to 0.7.12 the error disappears

**Comment by atinux** [comment]
Damn, it works for me with latest dependencies on https://github.com/nuxt-hub/starter

Do you have any specific configuration?

**Comment by michaelsieminski** [comment]
hm not really I only have database and blob enabled in the config

**Comment by atinux** [comment]
Could you try with https://github.com/nuxt-hub/core/releases/tag/v0.7.18 @michaelsieminski 

make sure to remove your lock file and install again

**Comment by michaelsieminski** [comment]
the problem is fixed in this version! Thank you alot for resolving this so quick!
