### ISSUE TITLE
[remote] strange "addRandomSuffix" behaviour

### ISSUE THREAD

**Issue by paulvonber** [nuxt-hub/core#286]
`addRandomSuffix` behaviour is a bit weird, even is set to false it still adding suffix, if I remove it completely then it works as expected, I mean it's not a problem, but could be quite confusing.

```js
hubBlob().put(file.name, file, {
    addRandomSuffix: false, // <-----
    prefix: 'images'
})
```

Would be nice if it does what it says :)

**Comment by atinux** [comment]
Thanks for reporting the issue (and sorry about this).<br><br>The issue appears when using `nuxt dev --remote`, will fix this ASAP.

**Comment by atinux** [comment]
You can upgrade to [v0.7.17](https://github.com/nuxt-hub/core/releases/tag/v0.7.17)
