### ISSUE TITLE
Failed to fetch remote storage: Project not found.

### ISSUE THREAD

**Issue by aaronLejeune** [nuxt-hub/core#290]
Hello there, 

Im creating a large webshop with NuxtHub (love it) but got issues when trying to connect to my local KV and Cache storage. 

### Context:
I want to store PSQL-api responses in KV storage with `nuxt multicache` but I cant seem to connect to the external KV storage.
This is what my files look like:

**nuxt.config.ts**
```
...
hub: {
  cache: true,
  kv: true,
}
```

**.data/hub/wrangler.toml**
```
[[kv_namespaces]]
binding = "KV"
id = "kv_default"
```

Weird thing is that I always see this in the nuxthub (both for KV and Cache), while in I can see that both KV and Cache are created in Cloudflare. 
![image](https://github.com/user-attachments/assets/3f597ca7-5b85-4177-80f1-c88408457252)

cloudflare project:
![image](https://github.com/user-attachments/assets/b33f50e8-0b64-457a-88d3-51d92a9b2cd7)

### What I tried:
- redeploy the project using `nuxthub deploy`
- relink the project to a newly created one using `npx nuxthub link`. Again KV and Caches are created but still get the same error

### Expected behavior
I cant seem to reproduce this issue easely so I hope the description can give enough context.
Would be nice to test this out locally. Looking forward to your reply :)

**Comment by atinux** [comment]
Hey,

Do you still have the installation page after deploying your project?

What is `nuxt multicache`?

**Comment by atinux** [comment]
Could you please upgrade to latest version (`v0.7.20`) and deploy agin?

**Comment by aaronLejeune** [comment]
Hi @atinux,

Thanks for waiting, was on vacation. 
I updated nuxthub to the latest version and deployed the website, but the issue does not seem to be resolved. 
```
Linked to https://admin.hub.nuxt.com/skargards-web-three/skargards-web                                      nuxt:hub 3:41:14 PM
Using production environment                                                                                nuxt:hub 3:41:14 PM
Using remote storage from http://skargards-web.pages.dev                                                    nuxt:hub 3:41:14 PM

ERROR  Failed to fetch remote storage: Project not found.                                                     nuxt:hub 3:41:14 PM
Make sure to deploy the project using nuxthub deploy or add the deployed URL as NUXT_HUB_PROJECT_URL environment variable.
```
I also added env variables `NUXT_HUB_PROJECT_KEY` and `NUXT_HUB_PROJECT_URL` with the correct settings just to make sure. On the local side, can it be CORS related by any chance?

I also tried to add some KV keys in Cloudlfare, but still no link with NuxtHub:
![image](https://github.com/user-attachments/assets/e82b9ad4-8e26-488e-8344-3c518b167f8e)
![image](https://github.com/user-attachments/assets/6727b0fa-a308-4ce7-ab81-95d3ddd89599)

**Comment by atinux** [comment]
it seems that [https://skargards-web.pages.dev/api/\_hub/manifest/](https://skargards-web.pages.dev/api/\_hub/manifest/) is sending back a 301, did you have any server middleware in place?

**Comment by atinux** [comment]
Feel free to re-open if update your server middleware is not the issue
