### ISSUE TITLE
Workers not working with $fetch

### ISSUE THREAD

**Issue by LeonardoRick** [nuxt-hub/core#297]
**Describe the bug**

I don't know if the error is related with nuxthub or cloudflare itself, but since I'm really struggling on finding a way to debug it, maybe you can give me some directions on it. 

I have a website that is calling `/api/recommendations`, `/api/quotes` and some other nuxt api endpoints on SSG step. I'm using `useFetch` for that and so far so good, my website is generated well with the information needed. You can check it in https://nuxthub.leonardorick.com (You can't see the network calls but the content of the website comes from this endpoints as was pre-generated).

The problem happens when I want to update the language on the website. Once I change the language to Portuguese on the language toggle, I recall this endpoints. Since I'm on client, I'm using `$fetch` and calling `/api/recommendations?locale=pt-BR`, `/api/quotes?locale=pt-BR`. At this moment I receive an error on every call: 

```json
{
    "url": "/api/recommendations?locale=pt-BR",
    "statusCode": 500,
    "statusMessage": "",
    "message": "Cannot read properties of undefined (reading 'document')",
    "stack": ""
}
```

[This is the code](https://github.com/cre8tive-studio/leonardorick/blob/main/server/api/recommendations.ts) of the implementation of my `/api/recommendations` in nuxt, as you can see, theres no `document` so it really seems something internal.

What is even weirder is that now that my page is already loaded, now I even can't call `/api/recommendations` without the query params. calling it would give the same `500` error above. I know the endpoint worked well on `SSG` and `useFetch` because the website is filled with the right information at the beginning, but then it stops working so the problem is not strictly related to the query params.

I have all my website working properly hosted in vercel and you can check it in https://leonardorick.com. I faced this issue trying to migrate everything to Cloudflare and NuxtHub and I really don't know what should I do about it. 

If you want to test the endpoints you can check this: 

`https://nuxthub.leonardorick.com/api/recommendations` [GET] [nuxthub/cloudflare-pages] (this doesn't work)
`https://leonardorick.com/api/recommendations` [GET] [vercel/vercel] (this works well)

**Steps to reproduce**
1. Go to https://nuxthub.leonardorick.com
2. Click on the top right language toggle (you might need to scroll down a bit so the menu appears)
3. Check the errors appearing on the console and network tab
4. You can also just call the endpoints provided above that are really the same thing and one works and the other don't

**Expected behavior**
The endpoint should work as expected and return the valid data as it happens in the vercel deployment.

I really wanted to migrate everything to cloudflare to be able to enable proxy on all my DNS endpoints so if anyone could give me some light on how to debug it or what might be the source of the problem I would really really appreciate it.

Thanks a lot for the library! It's really amazing.

**Comment by RihanArfan** [comment]
The issue is due to a bug accessing `process.env` with Cloudflare's `nodejs_compat` flag set. https://github.com/nuxt-hub/core/issues/294#issuecomment-2373747541

For now to fix the issue you can access environment variables from the request event.
```ts
const env = event.context.cloudflare?.env || process.env || {}
const url = process.env.PAYLOAD_GRAPHQL_URL as string;
```

**Comment by LeonardoRick** [comment]
You mean

```javascript
const url = env.PAYLOAD_GRAPHQL_URL as string;
```

right?

**Comment by atinux** [comment]
It should work with latest release, could you confirm?
