### ISSUE TITLE
Errors in the KV view/editor

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-hub/core#311]
Hello there !

There's some errors in the console when I go to the KV page of the admin panel. They seem to be related to cloudflare.
I don't know if it's related to my personal case neither if it's some serious errors, but I wanted to tell you !

<img width="1680" alt="374518039-82f9e4d4-165e-4064-9568-f20c731bda42" src="https://github.com/user-attachments/assets/8fafbb99-5961-4dcf-9d50-ff66404cd06c">

**Comment by atinux** [comment]
Could you hard reload the app?

**Comment by mathieunicolas** [comment]
You mean reloading with Maj + Cmd + R (firefox on macOS) ? It doesn't change anything

Actually the errors appear as soon as I go the the admin panel, even before I select a project. Noticed that it doesn't affect how well the app runs !

**Comment by mathieunicolas** [comment]
Oh, nevermind. I thought I disabled all the blockers with firefox and ublock origin to be sure it wasn't on my side, but I forgot the duckduckgo extension which was not in the toolbar and still on...
I'm sorry for the false alert !!
