### ISSUE TITLE
handlemultipartupload seems to no  work

### ISSUE THREAD

**Issue by germsb** [nuxt-hub/core#314]
**Describe the bug**
[handlemultipartupload](https://hub.nuxt.com/docs/features/blob#handlemultipartupload) systematically returns an error
```error
https://localhost:3000/api/files/multipart/create/google-chrome-stable_current_amd64.deb 400 (Bad Request)
Uncaught (in promise) FetchError: [POST] "/api/files/multipart/create/google-chrome-stable_current_amd64.deb": 400 Bad Request
    at async $fetch2 (ofetch.4747642d.mjs?v=d7c0ec42:304:15)
```

**Steps to reproduce**
Example [in the doc](https://hub.nuxt.com/docs/features/blob#handlemultipartupload) or [in the playground](https://github.com/nuxt-hub/core/blob/main/playground/app/pages/blob.vue) 

PS: I use remote storage for dev, and everything works normally apart from this

**Comment by atinux** [comment]
I cannot reproduce your issue, tested on:
- pnpm dev
- pnpm dev --remote
- deployed playground


https://github.com/user-attachments/assets/99b8332a-013f-45cf-b352-1392935e38c2

**Comment by germsb** [comment]
I copied and pasted the different APIs as well as the content of the blob.vue page into my project, and I’m still get the same error. I admit I don’t understand.

![Capture d’écran du 2024-10-11 20-21-13](https://github.com/user-attachments/assets/034d2b00-d855-40ad-9301-ce4224e33b20)

![Capture d’écran du 2024-10-11 20-22-20](https://github.com/user-attachments/assets/b4dcef7b-d017-44b8-8916-d920ec3ae708)

[Capture vidéo du 2024-10-11 20-41-37.webm](https://github.com/user-attachments/assets/6e7ba2d9-96e0-438c-93ce-dbb0718089fd)

**Comment by atinux** [comment]
Thank you so much for being so helpful on it, I can reproduce, will fix it quickly! Sorry about this!

**Comment by atinux** [comment]
Hey @germsb 

Could you try with:

```bash
pnpm add https://pkg.pr.new/nuxt-hub/core/@nuxthub/core@318
```

Then try again with `nuxi dev --remote` and confirm me that it fixes it? (no need to deploy anything normally)

**Comment by atinux** [comment]
Awesome ❤️

**Comment by zaosoula** [comment]
Hi @atinux, while using `"@nuxthub/core": "^0.7.33"` I got the exact same problem

**Comment by zaosoula** [comment]
Without enabling `remote`, the error message is more complete :
```
{
    "url": "/api/files/multipart/upload/Screenshot%202024-10-17%20at%2016.18.24.png?uploadId=tsRqrV0JSsAz-KU9YJsFbkkxmrrDF7fZa1MbfzYYw4ejgq8ynzD2oh0GaL3YCbacxZ1Q6fRXMMe7IE1rn9-h4PVdBqDQT2L6WgMyodS62Pg5TMulzscZJCTfu9N2Qf2Ea94X7Kcvng1LECbdZp0lPJZv0fAFc3WxOpVFVCTcXr0&partNumber=1",
    "statusCode": 400,
    "statusMessage": "",
    "message": "uploadPart: The specified multipart upload does not exist. (10024)",
    "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/h3/dist/index.mjs:78:15)</span>\n<span class=\"stack internal\">at uploadHandler (./node_modules/@nuxthub/core/dist/runtime/blob/server/utils/blob.js:345:13)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at handler (./node_modules/@nuxthub/core/dist/runtime/blob/server/utils/blob.js:397:15)</span>\n<span class=\"stack internal\">at Object.handleMultipartUpload (./node_modules/@nuxthub/core/dist/runtime/blob/server/utils/blob.js:415:20)</span>\n<span class=\"stack\">at Object.handler (./server/api/files/multipart/[action]/[...pathname].ts:2:1)</span>\n<span class=\"stack internal\">at async ./node_modules/h3/dist/index.mjs:1975:19</span>\n<span class=\"stack internal\">at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)</span></pre>"
}
```

![Screenshot 2024-10-18 at 12 04 47](https://github.com/user-attachments/assets/35c77185-1a75-48e8-bb85-902c17325999)

**Comment by zaosoula** [comment]
🙌 The error only appends when the filename contains spaces (ex: `Screenshot 2024-10-15 at 16.05.37.png`)

**Comment by atinux** [comment]
Could you test with 0.7.34 please?

**Comment by zaosoula** [comment]
@atinux Problem solved thank you!
