### ISSUE TITLE
Unable to see KV in Nuxt Hub UI

### ISSUE THREAD

**Issue by onmax** [nuxt-hub/core#321]
**Describe the bug**.

We have enabled `kv` in our [`nuxt.config.ts`](https://github.com/nimiq/prestaking-website/blob/main/nuxt.config.ts#L57-L59) and deployed it successfully.

However, we are unable to see the Nuxt Hub KV table.

**Steps to reproduce**.
Steps to reproduce the behaviour:
1. Deploy the Nuxt Hub project without `hub.kv` using the Nuxt Hub UI.
2. Enable `hub.kv = true` in Nuxt Config
3. Push it

**Expected behaviour

Don't see the empty state page and see the KV table.

![image](https://github.com/user-attachments/assets/42626673-94a1-4ce2-96f6-6b0108133a18)

**Comment by atinux** [comment]
What is the XHR error when going to the KV tab on client-side?

**Comment by sisou** [comment]
That last part is probably it.

**Comment by onmax** [comment]
Solved in this [commit](https://github.com/nimiq/prestaking-website/commit/aa229453b6b6365b9c8753e27885f0cc09f2bbcc)

Thank you
