### ISSUE TITLE
`hubAI` does not work in local development

### ISSUE THREAD

**Issue by danielroe** [nuxt-hub/core#325]
flagged up here:

> Hi there! I think this might have caused an issue where using `hubAI()` during local development now throws an error saying: `Missing Cloudflare AI binding (AI)`.

> The generated file `.data/hub/wrangler.toml` no longer includes the AI binding. Why was this change made? Why is it considered unused?

_Originally posted by @CernyMatej in https://github.com/nuxt-hub/core/issues/308#issuecomment-2413658130_

**Comment by atinux** [comment]
Should be fixed in https://github.com/nuxt-hub/core/releases/tag/v0.7.33
