### ISSUE TITLE
Unable to see the images in the Blob view

### ISSUE THREAD

**Issue by onmax** [nuxt-hub/core#326]
**Description of the bug**

Images fail to load in the NuxtHub admin and show an error with status code 500. The error indicates that the Fetch API is unable to retrieve the image URLs.

Here is some information that may be relevant:
- The image names contain `:`.
- This happens in a team. Is it possible that there are some security rules in the cloudflare account that prevent the images from loading?
- I am using [my own custom endpoint](https://github.com/nimiq/crypto-map/blob/onmax/nuxt/server/routes/images/%5B...pathname%5D.get.ts) to serve the image and it seems to work. So the images are uploading correctly.
- I don't see any errors or placeholders, maybe show a fallback?

<details><summary>Error from server</summary>
<p>

```json
{
    "url": "/api/teams/nimiq/projects/crypto-map/production/blob/location:bea8377e-42b0-4289-9b0e-d94bcb1565e2",
    "statusCode": 500,
    "status message": "",
    "message": "[GET] \"location:bea8377e-42b0-4289-9b0e-d94bcb1565e2\": <no response> Fetch API cannot load: location:bea8377e-42b0-4289-9b0e-d94bcb1565e2",
    "stack": ""
}

```

</p>
</details> 

![image](https://github.com/user-attachments/assets/d4fe9dbe-4d99-4da2-ba5b-d0c21154f386)

Thank you in advance! 🙌

**Comment by atinux** [comment]
If you right-click and open in a new tab? What is displayed? Any content type answered?

**Comment by onmax** [comment]
> If you right-click and open in a new tab? What is displayed? Any content type answered?

![image](https://github.com/user-attachments/assets/1e551080-479d-4acf-9e95-4163b62e22a4)

> Does it work in the devtools locally?

Using local storage does work.
Using the remote storage does not work.

![image](https://github.com/user-attachments/assets/654ecde4-1f4c-4622-a4d3-628337c50023)

**Comment by atinux** [comment]
Should be fixed now with https://github.com/nuxt-hub/core/releases/tag/v0.7.34

Make sure to update the dependency and deploy, then refresh the admin.

**Comment by onmax** [comment]
Yes, it worked. Thank you!
