### ISSUE TITLE
error: KV PUT failed: 400 Invalid expiration_ttl of 0

### ISSUE THREAD

**Issue by oritwoen** [nuxt-hub/core#328]
**Describe the bug**

I don't know how to reproduce this. I have a lot of traffic on the website, several dozen thousand visits a day (still a dozen or so users online), and from time to time I see an error in the logs such as in the attached screenshot.

This appeared after the last update with ttl for cache and I have no idea why it occurs. For all endpoints that have caching, I have maxAge greater than 0.

![Zrzut ekranu z 2024-10-17 19-54-45](https://github.com/user-attachments/assets/31171fee-52b4-43c3-8622-b4e7c00d12ca)

**Comment by atinux** [comment]
Could you test with v0.7.34?

**Comment by oritwoen** [comment]
After updating to `v0.7.34` I don't see this error anymore. I also feel like performance has improved 😅 Thanks!

**Comment by atinux** [comment]
Awesome 🙂
