### ISSUE TITLE
Gitlab: "Could not import branches"

### ISSUE THREAD

**Issue by exophunk** [nuxt-hub/core#353]
**Describe the bug**
I try to set up a project with gitlab. I've connected cloudflare to gitlab and that seems to work as I am able to select repositories. But when I select a respository, it fails to load branches and I cant select a branch. After that it's not possible to proceed and complete the setup

**Steps to reproduce**
in admin.hub.nuxt.com
1. new project
2. import a git repository
3. gitlab --> chose a repository
4. Toast message shows "Could not import branches". The network tab shows a 404 on `https://admin.hub.nuxt.com/api/teams/.../cloudflare/connections/gitlab/.../repos/.../.../branches`

Is this any kind of permission problem?
1. The repository is from a "team" i am part of
2. Inside clouldflare directly, there is no problem selecting the gitlab repo and seeing all branches. So the permission between cloudflare --> gitlab should be fine.

**Expected behavior**
I want to be able to connect a gitlab repository.

**Comment by atinux** [comment]
I just tested and it seems to work properly:

https://github.com/user-attachments/assets/03f7ebf5-70b8-4557-a44a-8bfcfd6613c3

I added a new fallback system if the branches could not be selected to you can manually add the branch in the text input, hope this solves your issue.

**Comment by exophunk** [comment]
That should solve the issue, as i added the branch name manually yesterday to the input field in a hacky way via devtools :-) Thanks!
