### ISSUE TITLE
Parameterized nuxthub link

### ISSUE THREAD

**Issue by bovium** [nuxt-hub/core#358]
**Is your feature request related to a problem? Please describe.**
I would like to be able to create new projects in hub.nuxt.com from a github pipeline ex. using a parameterized nuxthub link.

**Describe the solution you'd like**
Instead of the questions where you type the input on nuxthub link is would like syntax ala this:
nuxthub link --team "TeamName" --newproject --projectname "ProjectName" --region "Western Europe" --branch "master"

**Describe alternatives you've considered**
I consider wrapping the "nuxthub link" with some tool appropriate for that to automize this to have the same behavior as a parameterized command.

**Comment by atinux** [comment]
Wouldn't it better to use our REST API if we expose it or you rather use the CLI?

**Comment by bovium** [comment]
> Wouldn't it better to use our REST API if we expose it or you rather use the CLI?

Yes that would be perfect.

It would be very slick if I could do all the things I can do manually in the nuxthub UI through a Rest API.

What about authorization NUXT_HUB_USER_TOKEN should be used against the REST API I imagine?

**Comment by atinux** [comment]
You can actually do all the things with our REST API with the `NUXT_HUB_USER_TOKEN`, actually you can also create your own user token in the dashboard:

https://github.com/user-attachments/assets/2dad83e6-e06f-4d96-af7a-bd293e03d0ee

Then you can do the same actions as the CLI, checkout this file as it as most of the API actions:
https://github.com/nuxt-hub/cli/blob/main/src/utils/data.mjs
