### ISSUE TITLE
after use nuxthub deploy, page only appear Home font. 

### ISSUE THREAD

**Issue by vaesonshu** [nuxt-hub/core#360]
my project has successed in nuxthub, but open web, it only appear Home font in web page.

![2024-11-01_174312](https://github.com/user-attachments/assets/2735a5dc-6e7b-41b4-b353-7e3d1ff283cd)

![2024-11-01_170759](https://github.com/user-attachments/assets/4212315b-4561-474d-b6a3-4ab4eb8ce7dd)

this is my web link. https://nuxt-template-vaesonshu.nuxt.dev

**Comment by RihanArfan** [comment]
Your page is returning HTTP 500
![image](https://github.com/user-attachments/assets/0f189c30-373d-4769-9c73-a5460d1891cd)
![image](https://github.com/user-attachments/assets/cc3ab35f-dffb-4889-9572-f16f895b1196)

You can view the server logs from NuxtHub admin -> Deployments -> Server logs

**Comment by vaesonshu** [comment]
Thank you. I'll try to work it out.
