### ISSUE TITLE
Cannot access 'tc' before initialization

### ISSUE THREAD

**Issue by aligzl** [nuxt-hub/core#363]
**Describe the bug**
Hi, i cant deploy my app as getting error about hubDatabase during the deployment

17:48:42.892 Error: Failed to publish your Function. Got error: Uncaught ReferenceError: Cannot access 'tc' before initialization
  at chunks/nitro/nitro.mjs:1:588600 in useRuntimeConfig
  at chunks/nitro/nitro.mjs:1:225944 in requireNuxtHubFeature
  at chunks/nitro/nitro.mjs:1:444655 in hubDatabase
  at chunks/nitro/nitro.mjs:1:458639

**Steps to reproduce**
Deplyment Logs

**Comment by aligzl** [comment]
> What is displayed when your run `npx nuxi info`?

- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxthub/core@0.8.4, @nuxt/eslint@0.6.1, @nuxt/fonts@0.10.2, @nuxt/ui, @vueuse/nuxt@11.2.0, @nuxtjs/i18n@8.5.5, nuxt-security@2.0.0, nuxt-auth-utils@0.5.1
- Build Modules:    -

**Comment by aligzl** [comment]
i am also getting this error even i didnt update any deps during dev

[worker reload] [worker init]  .nuxt/dev/index.mjs failed 

i assume that this error comes from nuxt  related to [6712](https://github.com/primefaces/primevue/issues/6712)

**Comment by aligzl** [comment]
instaling   "nitropack": "2.9.7" and adding 
```
"overrides": {
  "nitropack": "2.9.7"
}
```

solved my issue for now

**Comment by pi0** [comment]
✅ Nitro [2.10.1](https://github.com/nitrojs/nitro/releases/tag/v2.10.1) is released with a fix. Recreating lock-file should solve the problem (tested against [reproduction](https://stackblitz.com/edit/nuxt-starter-vhvkfm?file=README.md)).

**Comment by aligzl** [comment]
Closing as fixed in Nitro [v2.10.1](https://github.com/nitrojs/nitro/releases/tag/v2.10.1)

**Comment by aligzl** [comment]
Hi Getting this error during deployment

Error: Failed to publish your Function. Got error: Uncaught Error: Missing Cloudflare DB binding (D1)
  at chunks/nitro/nitro.mjs:1:68337 in createError$1
  at chunks/nitro/nitro.mjs:1:489144 in hubDatabase
  at chunks/nitro/nitro.mjs:1:500109

**Comment by atinux** [comment]
Could you please try with nuxthub/core 0.8.5?

**Comment by aligzl** [comment]
> Could you please try with nuxthub/core 0.8.5?

Still same error with fallowing

```
Error: Failed to publish your Function. Got error: Uncaught Error: Missing Cloudflare DB binding (D1)
  at chunks/nitro/nitro.mjs:1:68337 in createError$1
  at chunks/nitro/nitro.mjs:1:489180 in hubDatabase
  at chunks/nitro/nitro.mjs:1:500032
```

```
------------------------------
- Operating System: Darwin
- Node Version:     v21.7.3
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxthub/core@0.8.5, @nuxt/eslint@0.6.1, @nuxt/fonts@0.10.2, @nuxt/ui, @vueuse/nuxt@11.2.0, @nuxtjs/i18n@9.0.0, nuxt-security@2.0.0, nuxt-auth-utils@0.5.1
- Build Modules:    -
------------------------------
```

**Comment by atinux** [comment]
How do you deploy your app @aligzl ?

**Comment by aligzl** [comment]
> How do you deploy your app @aligzl ?

trough github actions

**Comment by atinux** [comment]
Do you mind inviting me to your project? Did you change anything in the bindings of your project on Cloudflare?

**Comment by aligzl** [comment]
> Do you mind inviting me to your project? Did you change anything in the bindings of your project on Cloudflare?

I have invited you to my project and i did not touch anything in the bindings

**Comment by atinux** [comment]
I found the issue @aligzl 

You should not call `hubDatabase()` or `hubKV()` inside the `server/utils/` without wrapping them into a function:

```diff
- export const todoDb = new todoService(hubDatabase())
+ export const todoDb = () => new todoService(hubDatabase())
```

You will need to update `todoDb.findOneAndUpdate` to `todoDb().findOneAndUpdate` for example.

This is because the bindings are available only when the request comes in, so inside the event handlers, before this, they are not ready, thus the error happening (I believe Cloudflare try to run the code before deploying it).

**Comment by aligzl** [comment]
> I found the issue @aligzl
> 
> You should not call `hubDatabase()` or `hubKV()` inside the `server/utils/` without wrapping them into a function:
> 
> ```diff
> - export const todoDb = new todoService(hubDatabase())
> + export const todoDb = () => new todoService(hubDatabase())
> ```
> 
> You will need to update `todoDb.findOneAndUpdate` to `todoDb().findOneAndUpdate` for example.
> 
> This is because the bindings are available only when the request comes in, so inside the event handlers, before this, they are not ready, thus the error happening (I believe Cloudflare try to run the code before deploying it).

let me try,
But it was working before

Thanks for your kind help

**Comment by atinux** [comment]
It was an issue if it was working before I believe, it was probably related to how the chunks were generated with Nitro.

**Comment by aligzl** [comment]
It works as expected now 
 i think it's a good point to add it to the docs to avoid this kind of mistakes or approaches

Thanks

**Comment by veypi** [comment]
i got a same error. https://stackblitz.com/edit/nuxt-starter-3dapj6?file=app.config.ts

**Comment by Nicholaiii** [comment]
> Where do you think would be the best place?
Near examples of how `hubDatabase` is used, perhaps

I ran in to this issue when setting up the Drizzle ORM example, thinking it was wasteful to create a new database connection every time. 
![{45640C58-59E2-46C4-901B-11AE07D76AA6}](https://github.com/user-attachments/assets/8f15ea5f-e8b9-40c9-9c88-bb9b361e1439)

The error does not seem to be handled properly:
![{E8E6A486-A606-49FC-93BC-70587C907118}](https://github.com/user-attachments/assets/14b1a5e8-99a3-4f83-9dda-f74467eb4c85)
