### ISSUE TITLE
[Question] A way to specify the Node.js version for the deployment runtime

### ISSUE THREAD

**Issue by germsb** [nuxt-hub/core#368]
Hello,

Currently, when deploying, Node.js version 18.17.1 is used for the build process. Some of my dependencies, specifically @simplewebauthn/server, require Node.js 20 or higher, leading to compatibility warnings and potential runtime issues. 

Would it be possible to allow specifying a preferred Node.js version?

 Thank you in advance for your help

**Comment by atinux** [comment]
Hi @germsb 

You can change the node version with the `NODE_VERSION` env variable and redeploy your project.
