### ISSUE TITLE
[admin] 'Could not fetch project' error.

### ISSUE THREAD

**Issue by kamilmedrala** [nuxt-hub/core#370]
After logging into admin.hub.nuxt.com, I encounter an error message when attempting to open a project created 4 months ago. The project is not accessible despite being listed.

Steps to reproduce:

- Log in to admin.hub.nuxt.com.
- Navigate to the projects list.
- Attempt to open a project

![image](https://github.com/user-attachments/assets/43f0a464-a033-456e-a3a6-aa6ec58f217c)

```
{
    "url": "/api/teams/kamilmedrala/projects/shine-plan",
    "statusCode": 401,
    "statusMessage": "",
    "message": "Authentication error",
    "stack": ""
}
```

**Comment by atinux** [comment]
It seems that your Cloudflare API token is not valid anymore, could you please:
- Open https://admin.hub.nuxt.com/kamilmedrala/settings/cloudflare
- Click on "Connect another Cloudflare account"
- Click on "Create a token" and create the token with the required permission for your CF account
- Come back to NuxtHub Admin and save your token
- Navigate again to your project

**Comment by kamilmedrala** [comment]
Thank you for your support. The issue has been resolved.
