### ISSUE TITLE
Database - Create Trigger

### ISSUE THREAD

**Issue by Brianelvio** [nuxt-hub/core#372]
**Describe the bug**
When trying to create a trigger the migration will always fail.

My attempt:
```
CREATE TRIGGER update_users_timestamp 
AFTER UPDATE ON users
BEGIN
  UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
```

Error:
```
 ERROR  Failed to apply migration ./server/database/migrations/0002_adduserstimestamptrigger.sql
 D1_ERROR: incomplete input: SQLITE_ERROR
 ```

**Steps to reproduce**
1. Create a migration
2. Try to create a trigger
3. Run the migration

**Expected behavior**
Migration is able to handle triggers for SQLite.

**Comment by atinux** [comment]
Could you try to put all your statement in one line?

**Comment by Brianelvio** [comment]
> Could you try to put all your statement in one line?

Thanks, that has worked! Sorry for the late response here.
