### ISSUE TITLE
[Question] Can i use @nuxthub/core but in netlify?

### ISSUE THREAD

**Issue by matifanger** [nuxt-hub/core#379]
1. Can I use @nuxthub/core with Netlify/Vercel/self-hosting? 
I honestly love the idea of hosting on Cloudflare, but I'd just like to know.

2. When will these modules be released?
@nuxthub/auth
@nuxthub/email
@nuxthub/analytics 

Do we have an estimated date? I'm just asking because these ideas look amazing.

Thanks for your hard work guys!

**Comment by atinux** [comment]
1. Sorry this is not possible as this is already a lot of work to support well on provider with a great DX :)

2. I plan to have @nuxthub/auth early next year once we are out of beta and migrated to Workers!
