### ISSUE TITLE
Deployment status shows "building" despite successful deployment

### ISSUE THREAD

**Issue by michaelreinhard1** [nuxt-hub/core#380]
**Describe the bug**
Hi, just wanted to report this little bug I found. After a successful deployment, the deployment list page incorrectly displays the yellow "building" status indicator. This stays yellow even after refreshing the page or logging out and back in.

![Screenshot 2024-11-18 at 11-35-45 NuxtHub Admin Manage full-stack Nuxt apps on the edge  - michaelreinhard-neon - michaelreinhard1 - NuxtHub](https://github.com/user-attachments/assets/729e2a1a-e952-4910-83fa-d8039febc1ad)
![Screenshot 2024-11-18 at 11-32-16 Deployments - michaelreinhard-neon - michaelreinhard1 - NuxtHub](https://github.com/user-attachments/assets/c52b41b7-730c-4072-a525-c039e18a80be)

**Expected behavior**
The expected behavior is for the status to reflect "successful" once the deployment is complete.

**Comment by atinux** [comment]
@michaelreinhard1 please make sure to install the `@nuxthub/core` module as properly tracking the deployments when using the Cloudflare CI is hard without the module.

The module will also make sure everything works well for your Nuxt app on Cloudflare.

https://hub.nuxt.com/docs/getting-started/installation#add-to-a-nuxt-project
