### ISSUE TITLE
Marking existing migrations as applied

### ISSUE THREAD

**Issue by remihuigen** [nuxt-hub/core#382]
**Describe the bug**
I've upgrade @nuxthub/core from 0.7.x to the latest version. Since I was using Drizzle to handle migrations, I'm trying to follow the steps provided here: https://hub.nuxt.com/docs/features/database#migrating-from-drizzle-orm

upon using ``npx nuxthub database migrations mark-all-applied``

Im getting this error 👇

```
Marking 51 migrations as applied on http://localhost:3000...
 ERROR  Could not connect to http://localhost:3000/api/_hub/database/query                                                     8:08:30 AM


 WARN  Please make sure to run the Nuxt development server with npx nuxt dev.                                                  8:08:30 AM

✖ Could not mark all migrations as applied on http://localhost:3000.

 ERROR  [POST] "http://localhost:3000/api/_hub/database/query": <no response> fetch failed                                     8:08:30 AM
 
 ```

**Expected behavior**
As far as I'm understanding it, from 0.8.x onwards, using ``npx nuxt dev`` would [automatically apply all migrations found in sverver/database/migrations](https://hub.nuxt.com/docs/features/database#automatic-application). So we have to mark these as applied. But to achieve this, we'd need to run the development server, which is trying to run these migrations?

What am I missing here?

**Comment by remihuigen** [comment]
No I did not because I assume this would run the migrations before I marked them as applied? 

I'll give it a go anyways

**Comment by atinux** [comment]
> No I did not because I assume this would run the migrations before I marked them as applied?

It will try to run the migrations, if it fails, then it makes sense to run the `mark-all-applied` command as the database has already the tables created.

**Comment by remihuigen** [comment]
Sweet! That indeed works. 

I'm guessing the same thing goes from preview and production? So run ``npx nuxt dev --remote=production`` and ``npx nuxthub database migrations mark-all-applied --production`` in a second terminal?

**Comment by remihuigen** [comment]
Sweet, thanks for the quick reply
