### ISSUE TITLE
Any indication of when @nuxthub/auth will be ready? 

### ISSUE THREAD

**Issue by maclong9** [nuxt-hub/core#384]
It's the one thing stopping me from making the total switch over to Nuxt/NuxtHub

**Comment by yusufalitangoz** [comment]
https://github.com/nuxt-hub/core/issues/379#issuecomment-2482624930

**Comment by maclong9** [comment]
Beautiful @yusufalitangoz I adore the way the Nuxt ecosystem works with UI, content and studio it's just the auth solution that I have been waiting on. Thank you for the update.
