### ISSUE TITLE
Link deployment to commit

### ISSUE THREAD

**Issue by onmax** [nuxt-hub/core#385]
**Is your feature request related to a problem? Please describe.**

Direct link from deployment to the commit file

**Describe the solution you'd like**

In the screen /deployments/UUID, clicking on the repository should bring you to the commit that was deployed not the repository

**Describe alternatives you've considered**

Just look for the commit manually

**Additional context**

![image](https://github.com/user-attachments/assets/ab5fc543-9c17-49eb-ba9a-b6fb302f3aac)

**Comment by onmax** [comment]
Just noticed that the title goes to the commit 🤦‍♂️

**Comment by atinux** [comment]
No worries and thank you for the feedback!
