### ISSUE TITLE
Broken Hyperdrive recipe 

### ISSUE THREAD

**Issue by Idered** [nuxt-hub/core#387]
Hey @atinux 👋, yesterday I tried to setup Supabase + Drizzle + Hyperdrive and I spotted a little mistake in hyperdrive recipe: 
process.env.POSTGRES doesn't exist in eventHandler scope. I had to use this:

```
export default eventHandler(async (event) => {
  const hyperdrive = event.context?.cloudflare?.env?.POSTGRES
});
```

---

I've also implemented automatic drizzle migrations for dev and production, you can check full implementation here (it's still wip, based on nuxt hub implementation):

https://github.com/Idered/chalk.ist/tree/main/modules/drizzle and
https://github.com/Idered/chalk.ist/tree/main/server/database

Supabase + Drizzle + automatic migrations + Hyperdrive sounds like a good idea for new recipe :) Let me know if you need help with this

Thanks for your amazing work on the Nuxt ecosystem 🍻

**Comment by atinux** [comment]
Hi @Idered 

Did you deploy with latest version of nuxthub and the compatibility date?

I have this workaround that should make `process.env` work: https://github.com/nuxt-hub/core/blob/main/src/runtime/env.ts

**Comment by Idered** [comment]
in nuxt.config:

```
compatibilityDate: "2024-10-23",
```


in package.json:

```
"@nuxthub/core": "^0.8.7",
```

Suggested date in recipe is `compatibility_date = "2024-09-23"` so I guess it should be ok?

**Comment by atinux** [comment]
Bah we should set it to early November

**Comment by Idered** [comment]
Hey, I'll get back to this recipe after a little more testing. Closing for now
