### ISSUE TITLE
How to integrate Drizzle ORM?

### ISSUE THREAD

**Issue by kingyue737** [nuxt-hub/core#389]
> This is a question instead of an issue

According to the docs, we can make a composable

```ts
export function useDrizzle() {
  return drizzle(hubDatabase(), { schema })
}
```

Why couldn't we directly export the `db` instance in the utils instead of the above composable? 
```ts
const db = drizzle(/*...*/)
export db
```

What's the benefit of the way the docs recommend it?

---

I did the following before in my nuxt project but I found it is not recommended to use `process.env` in ambiant global contexts according the [docs of nitro](https://nitro.build/guide/configuration#local-development) (but the docs don't explain why).

```ts
// utils/db.ts
const queryClient = postgres(process.env.DB_URL!)
export const db = drizzle(queryClient)
```

So I guess the best practice is also a composable here?

```ts
// utils/db.ts
export function useDb(){
  const runtimeConfig = useRuntimeConfig()
  queryClient = postgres(runtimeConfig.db.url)
  return drizzle(queryClient)
}
```

Thanks in advance!

**Comment by atinux** [comment]
It's because the database is not binded yet when loading the utils file, which can cause issue at dev & build time.
