### ISSUE TITLE
[admin] Can't login to admin app

### ISSUE THREAD

**Issue by remihuigen** [nuxt-hub/core#403]
**Describe the bug**
For some reason, i can no longer login to the admin app with my github account. Navigating to https://admin.hub.nuxt.com/auth/github redirects me back to https://admin.hub.nuxt.com with a 401

![Screenshot 2024-12-23 at 12 39 25](https://github.com/user-attachments/assets/02b0dfdb-d522-43c7-bf22-ec5a3e484996)

After clearing cookies and other application data, and retrying, I'm getting these screens
<img width="1485" alt="Screenshot 2024-12-23 at 12 43 30" src="https://github.com/user-attachments/assets/b437586b-c1cc-4f57-9ad4-d0bb6a75da88" />

And then, after logging in with github 

![Screenshot 2024-12-23 at 12 42 51](https://github.com/user-attachments/assets/4d677741-5280-4e04-a845-060b6cf0fe33)

After reauthorizing, im being redirected again to https://admin.hub.nuxt.com/ with a 401

Not sure what is happening here?

**Comment by atinux** [comment]
Sorry about this, I forgot the read email permission in the GitHub App.

Should be good now!

**Comment by remihuigen** [comment]
Thanks for the quick fix!
