### ISSUE TITLE
appropriate way to run migrations

### ISSUE THREAD

**Issue by Sandros94** [nuxt-hub/core#46]
While reading NuxtHub's docs [I see a comment about](https://hub.nuxt.com/docs/recipes/hooks#onhubready) `only run migrations in development`:
https://github.com/nuxt-hub/core/blob/b36246d0e54ab465034282a12f502835bfd37c2d/docs/content/docs/3.recipes/1.hooks.md?plain=1#L17-L30

But wouldn't this use the Cloudflare's quota? (I imagine only while in remote)

Moreover, while reading Cloudflare's docs [about D1 migrations](https://developers.cloudflare.com/d1/reference/migrations/) I also see that they are supported via `.sql` files. How complex could it be to implement a local `migration` folder (alongside all Nuxt's folders) that is cloned to Worker's directory and handle migrations this way?

First time checking out both NuxtHub and Cloudflare 😜

**Comment by Atinux** [comment]
Hi @Sandros94 

I actually run my migrations in development to my staging or production database using `npx nuxt dev --remote`

It works well so far!

**Comment by Sandros94** [comment]
> I actually run my migrations in development to my staging or production database using `npx nuxt dev --remote`

Are you referring to the Nitro plugin for migrations or D1's `.sql` migrations?

I imagine the first

**Comment by Atinux** [comment]
Nitro plugin yes @Sandros94

**Comment by Atinux** [comment]
You can also take a look at https://hub.nuxt.com/docs/recipes/drizzle#migrations for usage with Drizzle ORM, this is what we use to build https://admin.hub.nuxt.com

**Comment by Sandros94** [comment]
> You can also take a look at https://hub.nuxt.com/docs/recipes/drizzle#migrations for usage with Drizzle ORM, this is what we use to build https://admin.hub.nuxt.com

That indeed was my current plan and started learning a few things locally with Drizzle + db0, with the main goal to migrate those tests into D1.

I'm closing this issue for cleanup, also since the operations are quite simple and easy to understand

**Comment by Atinux** [comment]
Check you emails @Sandros94 :)
