### ISSUE TITLE
#ccdfb21 (force preset) is breaking change

### ISSUE THREAD

**Issue by oritwoen** [nuxt-hub/core#93]
The change from the commit: [#ccdfb21](https://github.com/nuxt-hub/core/commit/ccdfb21) completely prevented me from using the project.

I have a project that for some reasons must use `cloudflare-module` as a preset and I am in the process of migrating the functionality and infrastructure to `cloudflare-pages` one by one.

In `v0.5.15` which enforces the `cloudflare-pages` preset, I cannot make any changes and deploy to `cloudflare-module` because this preset is overwritten with a different value.

I will note here that `cloudflare-module` works very well in `dev` and `production`. The entire `@nuxthub/core` works perfectly on both presets: `cloudflare-pages` and `cloudflare-module`.

I know because I have been using `@nuxthub/core` and the `cloudflare-module` preset in production for several days now and everything works.

At this moment I have pin version `v0.5.14` in the project.

**Comment by okydk** [comment]
I agree. As dynamic sub-domains is not supported on Pages yet, we're also forced to build as cloudflare worker/module.

**Comment by Atinux** [comment]
First of all, I am sorry that this break your applications.

Second, I am very pleased to see that it also works for `cloudflare-module`!

Let me open a PR to fix that, you will need to specify the preset in your `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  nitro: {
    preset: 'cloudflare-pages'
  }
})
```

Is it good for both of you @oritwoen @okydk ?

**Comment by Atinux** [comment]
You can now safely upgrade to `v0.5.16`
