### ISSUE TITLE
Cannot write file because it would overwrite input file... Why?

### ISSUE THREAD

**Issue by Cholicer** [nuxt-hub/core#98]
![image](https://github.com/nuxt-hub/core/assets/58261264/c8c5b6cd-8f3a-46f0-89a0-d16fcf81ff91)

**Comment by Cholicer** [comment]
its solved itlesf by reloading vscode wth

**Comment by Cholicer** [comment]
Why I need ro reload vscode window to solve this issue? How can I solve it without reloading?

**Comment by Teages** [comment]
try this https://github.com/antfu/eslint-config/issues/376#issuecomment-1890415385

**Comment by Atinux** [comment]
This issue is not related to NuxtHub itself
